# Generated by Django 4.1.6 on 2023-02-16 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(choices=[('TM', 'Модель техники'), ('EM', 'Модель двигателя'), ('TRM', 'Модель трансмиссии'), ('DAM', 'Модель ведущего моста'), ('SBM', 'Модель управляемого моста'), ('TOM', 'Вид ТО'), ('NOF', 'Характер отказа'), ('RM', 'Способ восстановления')], max_length=3)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('operating', models.PositiveIntegerField(default=0)),
                ('orders_number', models.CharField(max_length=64)),
                ('orders_date', models.DateField()),
                ('organization', models.CharField(max_length=64)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='info.directory')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.service_company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_date', models.DateField()),
                ('operating', models.PositiveIntegerField(default=0)),
                ('order_description', models.TextField()),
                ('used_spare_parts', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_complaint', to='info.directory')),
                ('order_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.directory')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_method', to='info.directory')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.service_company')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.CharField(max_length=64)),
                ('engine_serial_driver', models.CharField(max_length=64)),
                ('transmission_serial_number', models.CharField(max_length=64)),
                ('drive_axle_serial_number', models.CharField(max_length=64)),
                ('steerable_bridge_serial_number', models.CharField(max_length=64)),
                ('supply_contract', models.CharField(max_length=64)),
                ('date_of_shipment', models.DateField()),
                ('end_user', models.CharField(max_length=64)),
                ('delivery_adress', models.CharField(max_length=64)),
                ('equipment', models.CharField(max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.client')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_axle_model', to='info.directory')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='info.directory')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.service_company')),
                ('steerable_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steerable_bridge_model', to='info.directory')),
                ('technique_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_model', to='info.directory')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='info.directory')),
            ],
        ),
    ]
