# Generated by Django 4.1.6 on 2023-02-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(choices=[('TOM', 'Вид ТО'), ('NOF', 'Характер отказа'), ('RM', 'Способ восстановления')], max_length=3)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='directory',
            name='feature_name',
            field=models.CharField(choices=[('TM', 'Модель техники'), ('EM', 'Модель двигателя'), ('TRM', 'Модель трансмиссии'), ('DAM', 'Модель ведущего моста'), ('SBM', 'Модель управляемого моста')], max_length=3),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='order_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.directory2'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_method', to='info.directory2'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.directory2'),
        ),
    ]
