# Generated by Django 4.1.6 on 2023-02-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_rename_delivery_adress_car_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='technique_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_model', to='info.techniquemodel'),
        ),
    ]
