# Generated by Django 4.1.6 on 2023-02-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_car_technique_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_axle_model', to='info.driveaxlemodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='info.enginemodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steerable_bridge_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steerable_bridge_model', to='info.steerablebridgemodel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='info.transmissionmodel'),
        ),
    ]
