# Generated by Django 4.1.6 on 2023-03-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_car_drive_axle_model_alter_car_engine_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-orders_date']},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date']},
        ),
    ]
